import React, { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Bath, CalendarDays, CheckCircle, Heart, MessageCircle, PawPrint, Scissors, ShieldCheck, Sparkles, Star, Syringe } from "lucide-react";
import { motion } from "framer-motion";
import PublicLayout from "../../components/public/PublicLayout";

const API_PUBLIC = "https://spadodoguinho.com.br/api/public";
const heroDog = "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=90";
const pugDog = "https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?auto=format&fit=crop&w=900&q=90";

function money(value) { return Number(value || 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function iconFor(name = "", category = "") { const t = `${name} ${category}`.toLowerCase(); if (t.includes("tosa")) return Scissors; if (t.includes("vacina")) return Syringe; if (t.includes("spa")) return Sparkles; if (t.includes("banho")) return Bath; return PawPrint; }
function imageFor(name = "", category = "") { const t = `${name} ${category}`.toLowerCase(); if (t.includes("vacina")) return "/images/vacina-pet.svg"; if (t.includes("spa")) return "/images/spa-pet.svg"; if (t.includes("tosa") || t.includes("banho")) return "/images/banho-tosa.svg"; return "/images/hero-doguinho.svg"; }

const features = [
  [CalendarDays, "Agendamento fácil", "Agende em poucos cliques pelo site."],
  [Sparkles, "Higiene premium", "Produtos de alta qualidade e seguros."],
  [ShieldCheck, "Segurança", "Ambiente monitorado e profissionais treinados."],
  [Heart, "Carinho", "Tratamos seu pet com amor e dedicação."]
];

const fixedPlans = [
  ["Pequeno", "até 10kg", "/images/hero-doguinho.svg", "60,00", "90,00", "70,00"],
  ["Médio", "10,1kg a 25kg", "/images/banho-tosa.svg", "80,00", "120,00", "90,00"],
  ["Grande", "25,1kg a 40kg", "/images/spa-pet.svg", "100,00", "150,00", "110,00"],
  ["Gigante", "acima de 40kg", "/images/cliente-premium.svg", "120,00", "180,00", "130,00"]
];

export default function HomePage() {
  const [services, setServices] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => { async function load() { try { const res = await fetch(`${API_PUBLIC}/services`); const data = await res.json(); if (Array.isArray(data)) setServices(data.filter((s) => Number(s.active ?? 1) === 1)); } catch (err) { console.error("Erro ao carregar serviços:", err); } finally { setLoading(false); } } load(); }, []);

  return <PublicLayout><main className="relative overflow-hidden bg-[#03150d] text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_12%,rgba(34,197,94,.28),transparent_28%),radial-gradient(circle_at_80%_20%,rgba(245,158,11,.18),transparent_25%),linear-gradient(180deg,#03150d,#062415_45%,#02100a)]"/><div className="relative">
    <section className="max-w-7xl mx-auto px-6 pt-20 pb-10 grid lg:grid-cols-2 gap-12 items-center min-h-[760px]">
      <motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}>
        <span className="inline-flex items-center gap-2 rounded-full border border-yellow-400/25 bg-white/8 px-5 py-2 text-yellow-100 font-black shadow-xl"><PawPrint size={18}/> Cuidado que seu pet merece!</span>
        <h1 className="mt-8 text-5xl md:text-7xl font-black leading-[.98] tracking-tight">Seu pet limpo, <span className="text-green-300">cheiroso e feliz.</span></h1>
        <p className="mt-6 max-w-xl text-lg text-white/75 leading-relaxed">Banho, tosa, estética animal e muito mais, com todo carinho e segurança que seu melhor amigo merece.</p>
        <div className="mt-9 flex flex-wrap gap-4"><Link to="/agendamento" className="group rounded-2xl bg-green-600 hover:bg-green-700 px-8 py-4 font-black text-white shadow-xl shadow-green-900/30 flex items-center gap-3">Agendar agora <ArrowRight size={20} className="group-hover:translate-x-1 transition"/></Link><Link to="/servicos" className="rounded-2xl border border-yellow-400/35 bg-white/5 hover:bg-white/10 px-8 py-4 font-black text-yellow-100 flex items-center gap-3"><PawPrint size={20}/> Nossos serviços</Link></div>
        <div className="mt-10 grid grid-cols-3 gap-4 max-w-xl">{[["+3.500", "Pets atendidos"], ["6+", "Anos de experiência"], ["Online", "Agendamentos fáceis"]].map(([n,l]) => <div key={l} className="rounded-3xl border border-white/10 bg-white/7 p-5 backdrop-blur-xl"><div className="text-2xl md:text-3xl font-black">{n}</div><div className="text-white/60 text-sm mt-1">{l}</div></div>)}</div>
      </motion.div>
      <motion.div initial={{ opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .7, delay: .1 }} className="relative">
        <div className="absolute -inset-8 rounded-[56px] bg-green-500/10 blur-2xl"/><div className="relative rounded-[46px] border border-yellow-400/20 bg-white/8 p-6 shadow-2xl backdrop-blur-xl"><img src={heroDog} alt="Cachorro feliz no SPA do Doguinho" className="h-[500px] w-full object-cover rounded-[38px] shadow-2xl"/><div className="absolute -bottom-5 -left-2 md:left-[-26px] bg-[#fffaf0] text-slate-900 rounded-3xl p-5 shadow-2xl border border-yellow-100"><div className="flex items-center gap-3"><Star className="text-yellow-500 fill-yellow-500"/><div><p className="font-black">Atendimento 5 estrelas</p><p className="text-xs text-slate-500">Baseado em avaliações reais</p></div></div></div><div className="absolute right-6 bottom-8 w-20 h-20 rounded-full bg-green-800/80 border border-yellow-300/40 flex items-center justify-center text-yellow-200 shadow-2xl"><PawPrint size={38}/></div></div>
      </motion.div>
    </section>

    <section className="max-w-7xl mx-auto px-6 pb-16"><div className="rounded-[34px] border border-white/10 bg-white/5 backdrop-blur-xl shadow-2xl grid md:grid-cols-4 overflow-hidden">{features.map(([Icon,title,text],i)=><div key={title} className="p-8 border-white/10 md:border-r last:border-r-0"><Icon className="text-yellow-300 mb-5" size={34}/><h3 className="text-xl font-black">{title}</h3><p className="text-white/60 mt-2 text-sm leading-relaxed">{text}</p></div>)}</div></section>

    <section className="max-w-7xl mx-auto px-6 py-16"><div className="text-center max-w-3xl mx-auto"><span className="inline-flex items-center gap-2 rounded-full border border-yellow-400/25 bg-white/8 px-5 py-2 text-yellow-100 font-black"><PawPrint size={18}/> Nossos serviços</span><h2 className="mt-6 text-4xl md:text-6xl font-black">Tudo para o bem-estar do seu pet</h2><p className="mt-4 text-white/60">Serviços completos para deixar seu doguinho sempre lindo e saudável.</p></div><div className="mt-12 grid md:grid-cols-3 gap-7">{[["Banho & Tosa","/images/banho-tosa.svg","Higiene completa com muito carinho e produtos premium."],["Hidratação & Bem-estar","/images/vacina-pet.svg","Hidratação profunda para pelos macios e saudáveis."],["Spa Relaxante","/images/spa-pet.svg","Relaxamento e cuidado especial para o seu melhor amigo."]].map(([title,img,text])=><div key={title} className="rounded-[34px] bg-[#fffaf0] p-5 text-slate-900 shadow-2xl border border-yellow-100 hover:-translate-y-2 transition"><img src={img} alt={title} className="w-full h-56 object-cover rounded-[26px] bg-green-50"/><div className="p-4"><h3 className="text-2xl font-black">{title}</h3><p className="text-slate-500 mt-2 min-h-[48px]">{text}</p><Link to="/servicos" className="mt-5 inline-flex items-center gap-2 bg-green-100 hover:bg-green-200 text-green-800 px-5 py-3 rounded-2xl font-black">Saiba mais <PawPrint size={16}/></Link></div></div>)}</div></section>

    <section className="max-w-7xl mx-auto px-6 py-16"><div className="rounded-[38px] border border-white/10 bg-white/5 p-7 md:p-10 shadow-2xl"><div className="text-center max-w-3xl mx-auto"><span className="inline-flex items-center gap-2 rounded-full border border-yellow-400/25 bg-white/8 px-5 py-2 text-yellow-100 font-black"><PawPrint size={18}/> Escolha o porte do seu doguinho</span><h2 className="mt-6 text-4xl md:text-6xl font-black">Planos que cabem no seu bolso</h2><p className="mt-4 text-white/60">Preços justos para cuidados excepcionais.</p></div><div className="mt-12 grid md:grid-cols-2 xl:grid-cols-4 gap-5">{fixedPlans.map(([name,range,img,banho,combo,tosa])=><div key={name} className="rounded-[30px] bg-[#fffaf0] p-6 text-slate-900 shadow-xl border border-yellow-100"><div className="text-center"><h3 className="text-2xl font-black">{name}</h3><p className="text-sm text-slate-500">{range}</p><img src={img} alt={name} className="mt-5 mx-auto h-36 w-36 rounded-full object-cover bg-green-50 border border-green-100"/></div><div className="mt-6 space-y-3 text-sm"><PlanLine label="Banho" value={`R$ ${banho}`}/><PlanLine label="Banho e Tosa" value={`R$ ${combo}`}/><PlanLine label="Só Tosa" value={`R$ ${tosa}`}/></div><Link to="/agendamento" className="mt-6 block rounded-2xl bg-green-700 hover:bg-green-800 text-white text-center p-4 font-black">A partir de<br/><span className="text-xl">R$ {banho}</span></Link></div>)}</div><p className="mt-8 text-center text-yellow-100/75 text-sm">Os valores podem variar conforme necessidades específicas do seu pet.</p></div></section>

    {services.length > 0 && <section className="max-w-7xl mx-auto px-6 py-16"><div className="text-center max-w-3xl mx-auto"><span className="inline-flex items-center gap-2 bg-green-100 text-green-800 px-5 py-2 rounded-full font-black"><Sparkles size={18}/> Serviços cadastrados</span><h2 className="text-4xl md:text-6xl font-black mt-6">Catálogo conectado ao sistema</h2><p className="text-white/60 mt-4">Esses serviços vêm direto do painel administrativo.</p></div><div className="mt-12 grid md:grid-cols-2 xl:grid-cols-4 gap-6">{!loading && services.slice(0,8).map((service,index)=>{const Icon=iconFor(service.name,service.category); return <motion.div key={service.id || service.name} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:index*.04}} className="rounded-[30px] bg-white p-5 text-slate-900 shadow-2xl border border-green-100 hover:-translate-y-2 transition"><img src={imageFor(service.name,service.category)} alt={service.name} className="w-full h-40 object-cover rounded-[22px] mb-5 bg-green-50"/><div className="w-12 h-12 rounded-2xl bg-green-100 text-green-700 flex items-center justify-center"><Icon size={24}/></div><h3 className="text-xl font-black mt-4 break-words">{service.name}</h3><p className="text-slate-500 mt-2 text-sm min-h-[56px] break-words">{service.description || "Cuidado especial para seu pet."}</p><div className="mt-5 pt-5 border-t flex items-end justify-between"><div><div className="text-xs text-slate-400 font-bold">A partir de</div><div className="text-xl font-black text-green-700">{money(service.price)}</div></div><CheckCircle className="text-green-500"/></div></motion.div>})}</div></section>}

    <section className="max-w-7xl mx-auto px-6 py-16 pb-24"><div className="relative overflow-hidden rounded-[36px] bg-gradient-to-r from-green-700 via-emerald-600 to-green-500 p-8 md:p-12 shadow-2xl grid md:grid-cols-[1fr_auto] gap-8 items-center"><div><h2 className="text-4xl md:text-5xl font-black">Pronto para mimar seu doguinho?</h2><p className="mt-4 text-white/85 text-lg max-w-xl">Agende agora e proporcione o melhor para quem te dá tanto amor todos os dias.</p></div><div className="flex flex-col sm:flex-row gap-4"><Link to="/agendamento" className="bg-orange-400 hover:bg-orange-500 text-white px-8 py-4 rounded-2xl font-black flex items-center justify-center gap-2">Agendar agora <ArrowRight size={20}/></Link><a href="https://wa.me/5518997493722" target="_blank" rel="noreferrer" className="bg-white/15 hover:bg-white/25 border border-white/20 text-white px-8 py-4 rounded-2xl font-black flex items-center justify-center gap-2"><MessageCircle size={20}/> Falar no WhatsApp</a></div><img src={pugDog} alt="Pet no banho" className="absolute right-0 bottom-0 h-48 w-48 object-cover rounded-tl-[40px] opacity-25 hidden lg:block"/></div></section>
  </div></main></PublicLayout>;
}
function PlanLine({ label, value }) { return <div className="flex items-center justify-between gap-3"><span>{label}</span><b className="text-green-700">{value}</b></div>; }
