import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Bath, CalendarDays, CheckCircle, Clock, Heart, MessageCircle, PawPrint, Scissors, ShieldCheck, Sparkles, Star, Syringe } from "lucide-react";
import PublicLayout from "../../components/public/PublicLayout";

const photos = {
  hero: "https://images.pexels.com/photos/6131158/pexels-photo-6131158.jpeg?auto=compress&cs=tinysrgb&w=1800",
  bath: "https://images.pexels.com/photos/19145888/pexels-photo-19145888.jpeg?auto=compress&cs=tinysrgb&w=1200",
  towel: "https://images.pexels.com/photos/6131162/pexels-photo-6131162.jpeg?auto=compress&cs=tinysrgb&w=1200",
  grooming: "https://images.pexels.com/photos/19145882/pexels-photo-19145882.jpeg?auto=compress&cs=tinysrgb&w=1200",
  care: "https://images.pexels.com/photos/4432261/pexels-photo-4432261.jpeg?auto=compress&cs=tinysrgb&w=1200",
  vet: "https://images.pexels.com/photos/7468980/pexels-photo-7468980.jpeg?auto=compress&cs=tinysrgb&w=1200",
  happy: "https://images.pexels.com/photos/6816863/pexels-photo-6816863.jpeg?auto=compress&cs=tinysrgb&w=1200"
};

const services = [
  { title: "Banho Premium", icon: Bath, image: photos.bath, text: "Higiene delicada, hidratação e perfume na medida.", price: "R$ 60" },
  { title: "Tosa Boutique", icon: Scissors, image: photos.grooming, text: "Acabamento bonito e seguro para cada pelagem.", price: "R$ 80" },
  { title: "Spa Relaxante", icon: Sparkles, image: photos.towel, text: "Bem-estar, pele e pelagem com cuidado especial.", price: "R$ 95" },
  { title: "Vacinação", icon: Syringe, image: photos.vet, text: "Prevenção e orientação para manter a saúde em dia.", price: "R$ 120" }
];

const steps = [["01", "Recepção", "Chegada calma, identificação do pet e acolhimento."], ["02", "Avaliação", "Porte, pelagem, pele e comportamento observados."], ["03", "Cuidado", "Banho, tosa ou spa com produtos adequados."], ["04", "Entrega", "Finalização, perfume e orientação ao tutor."]];
const packages = [{ name: "Pequeno", detail: "até 10 kg", price: "R$ 60", time: "~1h" }, { name: "Médio", detail: "10 a 25 kg", price: "R$ 80", time: "~1h30" }, { name: "Grande", detail: "25 a 40 kg", price: "R$ 100", time: "~2h" }, { name: "Gigante", detail: "acima de 40 kg", price: "R$ 120", time: "~2h30" }];

export default function HomePage() {
  return (
    <PublicLayout>
      <main className="overflow-hidden bg-[#fff4ef] text-[#16322f]">
        <section className="relative bg-[#ffe8df] px-5 pb-14 pt-10 md:px-8 2xl:px-10">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_15%,rgba(25,83,78,.16),transparent_30%),radial-gradient(circle_at_82%_5%,rgba(201,119,78,.20),transparent_28%)]" />
          <div className="relative mx-auto grid max-w-[1680px] gap-8 xl:grid-cols-[1fr_1fr] xl:items-stretch">
            <div className="flex flex-col justify-center rounded-[46px] bg-white/38 p-8 backdrop-blur-sm md:p-12 xl:min-h-[660px]">
              <span className="inline-flex w-fit items-center gap-2 rounded-full border border-[#19534e]/10 bg-white/92 px-5 py-2 text-sm font-black text-[#19534e] shadow-sm"><Sparkles size={16} /> Pet boutique em Sud Mennucci</span>
              <h1 className="mt-7 max-w-4xl text-5xl font-black leading-[.92] tracking-tight text-[#16322f] md:text-7xl 2xl:text-8xl">Seu pet limpo, cheiroso e feliz sem estresse.</h1>
              <p className="mt-6 max-w-2xl text-lg leading-relaxed text-slate-700 md:text-xl">Banho, tosa, spa e vacinação em uma rotina premium, organizada e acolhedora do início ao fim.</p>
              <div className="mt-9 flex flex-wrap gap-4"><Link to="/agendamento" className="group inline-flex items-center gap-3 rounded-2xl bg-[#19534e] px-7 py-4 font-black text-white shadow-[0_20px_45px_rgba(25,83,78,.24)] transition hover:-translate-y-0.5 hover:bg-[#123f3b]"><CalendarDays size={19} /> Agendar agora <ArrowRight size={18} className="transition group-hover:translate-x-1" /></Link><a href="https://wa.me/5518997493722" target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 rounded-2xl border border-[#e4b8a7] bg-white px-7 py-4 font-black text-[#16322f] shadow-sm transition hover:-translate-y-0.5 hover:border-[#c9774e]"><MessageCircle size={19} /> WhatsApp</a></div>
              <div className="mt-10 grid max-w-2xl gap-3 sm:grid-cols-3">{[["+3.500", "pets atendidos"], ["5★", "experiência"], ["online", "agenda fácil"]].map(([value, label]) => <div key={label} className="rounded-3xl bg-white p-5 shadow-lg ring-1 ring-[#e4b8a7]/30"><div className="text-2xl font-black text-[#c9774e]">{value}</div><div className="mt-1 text-xs font-bold uppercase text-slate-500">{label}</div></div>)}</div>
            </div>
            <div className="grid gap-5 md:grid-cols-[.72fr_1fr] xl:min-h-[660px]">
              <div className="grid gap-5"><PhotoCard image={photos.bath} title="Banho cuidadoso" /><div className="rounded-[34px] bg-[#19534e] p-7 text-white shadow-xl"><div className="flex gap-1 text-[#f4c86a]">{[1, 2, 3, 4, 5].map((item) => <Star key={item} size={18} fill="currentColor" />)}</div><h3 className="mt-4 text-2xl font-black">Atendimento tranquilo</h3><p className="mt-2 text-white/75">Cuidado com higiene, segurança e carinho real.</p></div></div>
              <div className="relative overflow-hidden rounded-[46px] bg-slate-200 shadow-2xl ring-1 ring-black/5"><img src={photos.hero} alt="Pet limpo enrolado em toalha" className="h-full min-h-[520px] w-full object-cover" /><div className="absolute bottom-6 left-6 right-6 rounded-[28px] bg-white/90 p-5 shadow-2xl backdrop-blur"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#e6f3ef] text-[#19534e]"><ShieldCheck size={28} /></div><div><div className="font-black text-[#16322f]">Rotina segura</div><p className="mt-1 text-sm text-slate-500">Do agendamento até a entrega do pet.</p></div></div></div></div>
            </div>
          </div>
        </section>

        <section className="mx-auto grid max-w-[1680px] gap-5 px-5 py-12 md:grid-cols-4 md:px-8 2xl:px-10">{[[CalendarDays, "Agenda prática", "Reserve pelo site em poucos minutos."], [Sparkles, "Produtos premium", "Shampoos e finalizadores adequados."], [ShieldCheck, "Ambiente seguro", "Higiene, organização e atenção."], [Heart, "Carinho real", "Cada pet tratado com calma e respeito."]].map(([Icon, title, text]) => <Feature key={title} Icon={Icon} title={title} text={text} />)}</section>
        <section className="mx-auto max-w-[1680px] px-5 py-12 md:px-8 2xl:px-10"><div className="grid gap-10 xl:grid-cols-[.75fr_1.25fr] xl:items-end"><div><span className="inline-flex rounded-full bg-[#e6f3ef] px-5 py-2 text-sm font-black text-[#19534e]">Serviços</span><h2 className="mt-5 text-4xl font-black leading-tight md:text-6xl">Escolha o cuidado ideal.</h2><p className="mt-4 text-lg text-slate-600">Serviços com preço claro, fotos bonitas e caminho rápido para agendar.</p></div><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">{services.map((service) => <ServiceCard key={service.title} {...service} />)}</div></div></section>
        <section className="px-5 py-16 md:px-8 2xl:px-10"><div className="mx-auto grid max-w-[1680px] gap-8 overflow-hidden rounded-[42px] bg-[#19534e] p-8 text-white shadow-2xl md:p-12 xl:grid-cols-[.7fr_1.3fr] xl:items-center"><div><span className="inline-flex rounded-full bg-white/10 px-5 py-2 text-sm font-black text-[#ffe8df]">Experiência</span><h2 className="mt-5 text-4xl font-black leading-tight md:text-6xl">Um fluxo simples e confiável.</h2><p className="mt-5 max-w-xl text-lg leading-relaxed text-white/75">O tutor entende tudo: chegada, avaliação, cuidado e entrega.</p><Link to="/agendamento" className="mt-8 inline-flex items-center gap-3 rounded-2xl bg-[#f4c86a] px-7 py-4 font-black text-[#16322f] transition hover:bg-[#ffd97c]">Agendar atendimento <ArrowRight size={18} /></Link></div><div className="grid gap-4 md:grid-cols-4">{steps.map(([number, title, text]) => <StepCard key={number} number={number} title={title} text={text} />)}</div></div></section>
        <section className="mx-auto max-w-[1680px] px-5 py-10 md:px-8 2xl:px-10"><div className="grid gap-8 xl:grid-cols-[.9fr_1.1fr]"><div className="rounded-[36px] bg-white p-8 shadow-xl ring-1 ring-[#e4b8a7]/30"><span className="inline-flex rounded-full bg-[#e6f3ef] px-5 py-2 text-sm font-black text-[#19534e]">Pacotes</span><h2 className="mt-5 text-4xl font-black leading-tight md:text-5xl">Preço por porte, explicado sem complicar.</h2><p className="mt-4 text-slate-600">O valor e tempo mudam conforme porte e necessidade do pet.</p><img src={photos.care} alt="Kit de cuidado pet" className="mt-8 h-72 w-full rounded-[28px] object-cover" /></div><div className="grid gap-5 md:grid-cols-2">{packages.map((item) => <PackageCard key={item.name} {...item} />)}</div></div></section>
        <section className="mx-auto max-w-[1680px] px-5 py-16 md:px-8 2xl:px-10"><div className="grid gap-5 md:grid-cols-[1.1fr_.9fr_1fr]"><GalleryPhoto image={photos.grooming} title="Tosa com acabamento" /><GalleryPhoto image={photos.towel} title="Pós-banho confortável" tall /><GalleryPhoto image={photos.happy} title="Rotina com carinho" /></div></section>
        <section className="px-5 pb-16 md:px-8 2xl:px-10"><div className="mx-auto max-w-[1680px] overflow-hidden rounded-[40px] bg-[#c9774e] shadow-2xl"><div className="grid gap-8 p-8 text-white md:p-10 xl:grid-cols-[1fr_auto] xl:items-center"><div><h2 className="text-4xl font-black md:text-5xl">Pronto para deixar seu pet impecável?</h2><p className="mt-3 max-w-3xl text-white/85">Agende banho, tosa ou spa e ofereça uma experiência premium para seu melhor amigo.</p></div><div className="flex flex-wrap gap-4"><Link to="/agendamento" className="inline-flex items-center gap-2 rounded-2xl bg-white px-7 py-4 font-black text-[#c9774e] transition hover:bg-[#fff4ef]"><CalendarDays size={18} /> Agendar agora</Link><a href="https://wa.me/5518997493722" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-2xl border border-white/30 px-7 py-4 font-black text-white transition hover:bg-white/10"><MessageCircle size={18} /> WhatsApp</a></div></div></div></section>
      </main>
    </PublicLayout>
  );
}

function PhotoCard({ image, title }) { return <div className="relative overflow-hidden rounded-[34px] bg-slate-200 shadow-xl"><img src={image} alt={title} className="h-[310px] w-full object-cover" /><div className="absolute bottom-4 left-4 rounded-full bg-white/90 px-4 py-2 text-sm font-black text-[#16322f] shadow"><CheckCircle size={16} className="mr-2 inline text-[#19534e]" />{title}</div></div>; }
function Feature({ Icon, title, text }) { return <div className="rounded-[28px] bg-white p-6 shadow-sm ring-1 ring-[#e4b8a7]/30 transition hover:-translate-y-1 hover:shadow-xl"><Icon className="text-[#19534e]" size={32} /><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{text}</p></div>; }
function ServiceCard({ title, icon: Icon, image, text, price }) { return <article className="group overflow-hidden rounded-[30px] bg-white shadow-xl ring-1 ring-[#e4b8a7]/30 transition hover:-translate-y-1"><div className="relative h-52 overflow-hidden"><img src={image} alt={title} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute left-5 top-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-white text-[#19534e] shadow-xl"><Icon size={24} /></div></div><div className="p-6"><h3 className="text-xl font-black">{title}</h3><p className="mt-3 min-h-[70px] text-sm text-slate-600">{text}</p><div className="mt-5 flex items-end justify-between border-t border-[#f1d8cd] pt-5"><span className="text-xs font-bold text-slate-400">A partir de</span><strong className="text-2xl text-[#c9774e]">{price}</strong></div></div></article>; }
function StepCard({ number, title, text }) { return <div className="rounded-[28px] border border-white/10 bg-white/10 p-5"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#f4c86a] font-black text-[#16322f]">{number}</span><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm text-white/70">{text}</p></div>; }
function PackageCard({ name, detail, price, time }) { return <div className="rounded-[30px] bg-white p-6 shadow-xl ring-1 ring-[#e4b8a7]/30 transition hover:-translate-y-1"><div className="flex items-start justify-between gap-4"><div><h3 className="text-2xl font-black">{name}</h3><p className="mt-1 text-slate-500">{detail}</p></div><PawPrint className="text-[#19534e]" size={30} /></div><p className="mt-8 text-sm font-bold text-slate-400">Banho a partir de</p><div className="mt-1 text-4xl font-black text-[#c9774e]">{price}</div><div className="mt-5 flex items-center gap-2 text-slate-600"><Clock size={18} />{time}</div><Link to="/agendamento" className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#19534e] px-5 py-4 font-black text-white transition hover:bg-[#123f3b]">Agendar <ArrowRight size={18} /></Link></div>; }
function GalleryPhoto({ image, title, tall = false }) { return <div className={`group relative overflow-hidden rounded-[34px] bg-slate-200 shadow-xl ${tall ? "md:-mt-10" : ""}`}><img src={image} alt={title} className="h-[430px] w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/58 via-transparent to-transparent" /><div className="absolute bottom-5 left-5 right-5"><div className="inline-flex items-center gap-2 rounded-full bg-white/90 px-4 py-2 font-black text-[#16322f] shadow-lg"><CheckCircle size={17} className="text-[#19534e]" />{title}</div></div></div>; }
