name: Build Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências frontend
        working-directory: frontend
        run: npm install

      - name: Gerar build frontend
        working-directory: frontend
        run: npm run build

      - name: Commitar pasta dist
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Gerar build frontend
          file_pattern: frontend/dist
