name: Build Frontend

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: build-frontend
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Atualizar branch
        run: git pull --rebase origin main

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências frontend
        working-directory: frontend
        run: npm install

      - name: Gerar build frontend
        working-directory: frontend
        run: npm run build

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Salvar pasta dist
        run: |
          git add frontend/dist
          git commit -m "Gerar build frontend" || echo "Sem alterações para commitar"
          git push origin main
